import React,{useState} from 'react'
import * as XLSX from 'xlsx'
export default function Reports(){
  const [report,setReport]=useState('currentStock')
  const exportCurrentStockCSV=()=>{const csv='itemno,description,unit,price,quantity\nSKU001,Keyboard,pc,450,45\nSKU002,Mouse,pc,250,100';const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='current_stock.csv';a.click()}
  const exportItemsXLSX=()=>{const rows=[{itemno:'SKU001',description:'Keyboard',unit:'pc',price:450},{itemno:'SKU002',description:'Mouse',unit:'pc',price:250},];const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,'Items');XLSX.writeFile(wb,'items.xlsx')}
  return (<div className="space-y-4">
    <div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Reports</h2><div className="flex items-center gap-2"><select value={report} onChange={e=>setReport(e.target.value)} className="px-3 py-2 rounded border dark:bg-gray-900"><option value="currentStock">Current Stock</option><option value="items">Items (Excel)</option></select>{report==='currentStock'?<button onClick={exportCurrentStockCSV} className="px-3 py-2 bg-indigo-600 text-white rounded">Download CSV</button>:<button onClick={exportItemsXLSX} className="px-3 py-2 bg-indigo-600 text-white rounded">Download Excel</button>}</div></div>
    <div className="bg-white dark:bg-gray-800 p-3 rounded shadow"><h3 className="font-semibold mb-2">Preview</h3>{report==='currentStock'?(<table className="min-w-full text-sm"><thead><tr className="text-left text-gray-500 dark:text-gray-300"><th>Item No</th><th>Description</th><th>Unit</th><th>Price</th><th>Qty</th></tr></thead><tbody><tr><td>SKU001</td><td>Keyboard</td><td>pc</td><td>450</td><td>45</td></tr><tr><td>SKU002</td><td>Mouse</td><td>pc</td><td>250</td><td>100</td></tr></tbody></table>):(<table className="min-w-full text-sm"><thead><tr className="text-left text-gray-500 dark:text-gray-300"><th>Item No</th><th>Description</th><th>Unit</th><th>Price</th></tr></thead><tbody><tr><td>SKU001</td><td>Keyboard</td><td>pc</td><td>450</td></tr><tr><td>SKU002</td><td>Mouse</td><td>pc</td><td>250</td></tr></tbody></table>)}</div>
  </div>)}
